// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://emxwyjxfubqhmbpamgbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVteHd5anhmdWJxaG1icGFtZ2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0MTAwMzgsImV4cCI6MjA4Njk4NjAzOH0.xsvMr3zCLVIl1LlzJmAwjFil44MTSc9Z9lHoCALozwo";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);